-- MySQL Script generated by MySQL Workbench
-- qua 05 mar 2025 11:36:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_leilao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_leilao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_leilao` DEFAULT CHARACTER SET utf8 ;
USE `bd_leilao` ;

-- -----------------------------------------------------
-- Table `bd_leilao`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_leilao`.`tb_categoria` (
  `id_tb_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_tb_categoria` VARCHAR(45) NOT NULL,
  `descricao_tb_categoria` VARCHAR(45) NOT NULL,
  `status_tb_categoria` ENUM('0', '1') NULL DEFAULT '1',
  `data_cadastro_tb_categoria` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tb_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_leilao`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_leilao`.`tb_produto` (
  `id_tb_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_tb_produto` VARCHAR(255) NOT NULL,
  `descricao_tb_produto` VARCHAR(255) NOT NULL,
  `valor_min_tb_produto` DOUBLE NOT NULL,
  `anexo_tb_produto` LONGTEXT NOT NULL,
  `status_tb_produto` ENUM('0', '1') NULL DEFAULT '1',
  `data_cadastro_tb_produto` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_categoria_tb_produto` INT NOT NULL,
  PRIMARY KEY (`id_tb_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`id_categoria_tb_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`id_categoria_tb_produto`)
    REFERENCES `bd_leilao`.`tb_categoria` (`id_tb_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_leilao`.`tb_leilao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_leilao`.`tb_leilao` (
  `tb_leilao` INT NOT NULL AUTO_INCREMENT,
  `status_tb_leilao` ENUM('0', '1') NOT NULL,
  `valor_tb_leilao` DOUBLE NOT NULL,
  `data_hora_cadastro_tb_leilao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_produto_tb_leilao` INT NOT NULL,
  `valor_min_tb_leilao` DOUBLE NOT NULL,
  PRIMARY KEY (`tb_leilao`),
  INDEX `fk_tb_leilao_tb_produto1_idx` (`id_produto_tb_leilao` ASC) VISIBLE,
  CONSTRAINT `fk_tb_leilao_tb_produto1`
    FOREIGN KEY (`id_produto_tb_leilao`)
    REFERENCES `bd_leilao`.`tb_produto` (`id_tb_produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_leilao`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_leilao`.`tb_usuario` (
  `id_tb_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_tb_usuario` VARCHAR(255) NOT NULL,
  `usuario_tb_usuario` VARCHAR(50) NOT NULL,
  `senha_tb_usuario` VARCHAR(50) NOT NULL,
  `permissao_tb_usuario` ENUM('0', '1') NOT NULL,
  `status_tb_usuario` ENUM('0', '1') NULL DEFAULT '1',
  `data_cadastro_tb_usuario` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `telefone_tb_usuario` VARCHAR(45) NOT NULL,
  `cpf_tb_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tb_usuario`),
  UNIQUE INDEX `usuario_tb_usuario_UNIQUE` (`usuario_tb_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_leilao`.`tb_lance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_leilao`.`tb_lance` (
  `id_tb_lance` INT NOT NULL AUTO_INCREMENT,
  `id_leilao_tb_lance` INT NOT NULL,
  `id_usuario_tb_lance` INT NOT NULL,
  `valor_tb_lance` DOUBLE NOT NULL,
  `data_hora_cadastro_tb_lance` DATETIME NOT NULL,
  INDEX `fk_tb_lance_tb_leilao1_idx` (`id_leilao_tb_lance` ASC) VISIBLE,
  INDEX `fk_tb_lance_tb_usuario1_idx` (`id_usuario_tb_lance` ASC) VISIBLE,
  PRIMARY KEY (`id_tb_lance`),
  CONSTRAINT `fk_tb_lance_tb_leilao1`
    FOREIGN KEY (`id_leilao_tb_lance`)
    REFERENCES `bd_leilao`.`tb_leilao` (`tb_leilao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_lance_tb_usuario1`
    FOREIGN KEY (`id_usuario_tb_lance`)
    REFERENCES `bd_leilao`.`tb_usuario` (`id_tb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
